[package]
name = "strata-bridge-exec"
version = "0.1.0"
edition = "2024"
description = "Executors for the Strata Bridge"

[lints]
workspace = true

[dependencies]
algebra.workspace = true
btc-tracker.workspace = true
operator-wallet.workspace = true
secret-service-client.workspace = true
secret-service-proto.workspace = true
strata-bridge-connectors.workspace = true
strata-bridge-counterproof.workspace = true
strata-bridge-db.workspace = true
strata-bridge-p2p-service.workspace = true
strata-bridge-p2p-types.workspace = true
strata-bridge-primitives.workspace = true
strata-bridge-proof.workspace = true
strata-bridge-proof-common.workspace = true
strata-bridge-sm.workspace = true
strata-bridge-tx-graph.workspace = true

strata-asm-proto-bridge.workspace = true
strata-asm-proto-bridge-txs.workspace = true
strata-asm-rpc = { workspace = true, features = ["client"] }
strata-codec.workspace = true
strata-crypto.workspace = true
strata-identifiers.workspace = true
strata-l1-txfmt.workspace = true
strata-mosaic-client-api.workspace = true
zkaleido.workspace = true
zkaleido-sp1-groth16-verifier = { workspace = true, optional = true }

bdk_wallet.workspace = true
bitcoin.workspace = true
bitcoin-bosd = { workspace = true, features = ["address"] }
bitcoind-async-client.workspace = true
borsh.workspace = true
foundationdb.workspace = true
futures.workspace = true
jsonrpsee = { workspace = true, features = ["client"] }
metrics.workspace = true
musig2.workspace = true
ssz.workspace = true
terrors.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
strata-bridge-test-utils.workspace = true

bdk_bitcoind_rpc.workspace = true
corepc-node.workspace = true
operator-wallet = { workspace = true, features = ["test-utils"] }
tempfile.workspace = true

[features]
default = []
sp1 = [
  "strata-bridge-proof/sp1",
  "strata-bridge-counterproof/sp1",
  "dep:zkaleido-sp1-groth16-verifier",
]
